#!/usr/bin/env bash
#ALPHABETICALLY: Application->Data->Network->Physical->Presentation->Session->Transport
#LEVEL: Physical->Data->Network->Transport->Session->Presentation->Application
RANDON:Presentation->Transport->Session->Data->Application->Network->Physical
