#!/usr/bin/env bash
#Script that displays all the listening ports for this device.
echo "Active Internet connections (only servers)"
echo "proto Recv-Q send-Q Local Address		Foriegn Address		State		PID/Program Name"
ss -tulnep | awk '$1 == "listen" {print $1, $5, $6}' | while read line; do
proto=$(echo $line | awk '{print $1}')
port=$(echo $line | awk '{print $2}')
	local_address=$(echo $line | awk '{print $3}')
	pid_pro=$(echo $line | awk '{print $4}')

	pid=$(echo $pid_pro | cut -d '/' -f 1)
	program=$(echo $pid_pro | cut -d '/' -f 2-)

	printf "%-5s %-9s %-23s %-22s %s\n" "$proto" "$port" "$local_address" "LISTEN" "$pid_pro"
done
