#!/usr/bin/env bash

# Function to handle SIGTERM
handle_sigterm() {
    echo "I am invincible!!!"
}

# Trap SIGTERM signal and call handle_sigterm function
trap handle_sigterm SIGTERM

# Infinite loop to print the message and sleep
while true; do
    echo "To infinity and beyond"
    sleep 2
done

